In [1]:
import pandas as pd

df = pd.read_csv("../data/clean_orders.csv")

df.head()

   customer_id  order_id           order_date  quantity  price  order_value
0      17850.0    536365  2010-12-01 08:26:00         6   2.55        15.30
1      17850.0    536365  2010-12-01 08:26:00         6   3.39        20.34
2      17850.0    536365  2010-12-01 08:26:00         8   2.75        22.00
3      17850.0    536365  2010-12-01 08:26:00         6   3.39        20.34
4      17850.0    536365  2010-12-01 08:26:00         6   3.39        20.34

In [2]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [3]:
snapshot_date = df['order_date'].max() + pd.Timedelta(days=1)

In [4]:
customer_df = df.groupby('customer_id').agg({
    'order_date': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'order_value': 'sum'
}).reset_index()

customer_df.columns = [
    'customer_id',
    'recency_days',
    'total_orders',
    'total_spent'
]

customer_df.head()

   customer_id  recency_days  total_orders  total_spent
0      12346.0           326             1     77183.60
1      12347.0             2             7      4310.00
2      12348.0            75             4      1797.24
3      12349.0            19             1      1757.55
4      12350.0           310             1       334.40

In [5]:
customer_df.to_csv("../data/customer_metrics.csv", index=False)