In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("../data/online_retail_II.csv", encoding="latin1")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  object
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [8]:
df = df[[
    "Customer ID",
    "Invoice",
    "InvoiceDate",
    "Quantity",
    "Price"
]]

In [11]:
df.columns = [
    "customer_id",
    "order_id",
    "order_date",
    "quantity",
    "price"
]

In [12]:
df = df.dropna(subset=["customer_id"])

In [13]:
df = df[df["quantity"] > 0]

In [14]:
df["order_value"] = df["quantity"] * df["price"]

In [16]:
df["order_date"] = pd.to_datetime(df["order_date"], format="%m/%d/%Y %H:%M")

In [17]:
df.head()
df.describe()

,customer_id,order_date,quantity,price,order_value
count,397925.000000,397925,397925.000000,397925.000000,397925.000000
mean,15294.308601,2011-07-10 23:44:09.817126400,13.021793,3.116212,22.394737
min,12346.000000,2010-12-01 08:26:00,1.000000,0.000000,0.000000
25%,13969.000000,2011-04-07 11:12:00,2.000000,1.250000,4.680000
50%,15159.000000,2011-07-31 14:39:00,6.000000,1.950000,11.800000
75%,16795.000000,2011-10-20 14:33:00,12.000000,3.750000,19.800000
max,18287.000000,2011-12-09 12:50:00,80995.000000,8142.750000,168469.600000
std,1713.172738,NaN,180.419984,22.096773,309.055200

In [18]:
df.to_csv("../data/clean_orders.csv", index=False)